#! /bin/sh
###
# this is linux start file
#
#
#
. /etc/rc.d/init.d/functions

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin/
WORKING=/home/liveupdate/liveupdate-node
CONFIG_FILE=$WORKING/configuration.json

EXEC=$WORKING/index.js
PIDFILE=/var/run/liveupdate.pid
PROG="liveupdate"
OPTS="--path $WORKING --pidfile $PIDFILE --config $CONFIG_FILE & > /dev/null"


#[ -e /etc/sysconfig/$PROG ] && . /etc/sysconfig/$PROG

lockfile=/var/lock/subsys/$PROG



rh_status_q() {
    status $PROG >/dev/null 2>&1
}


case "$1" in
  start)
    [ -x $EXEC ] || exit 5
    [ -d $WORKING ] || exit 6
    echo -n $"Starting $PROG: "
    daemon $EXEC $OPTS &
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    ;;
  stop)
    echo -n $"Stopping $PROG: "
    if [ -f $PIDFILE ] ; then
        killproc -p $PIDFILE
    else
        failure $"Stopping $PROG"
    fi
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile $PIDFILE

    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status $PROG  && exit 0 || exit $?
    ;;
  condrestart|try-restart)
    rh_status_q || exit 0
    restart
    ;;
  *)
    echo "Usage: /etc/init.d/liveupdate {start|stop|restart|force-reload|status}"
    exit 2
    ;;
esac

exit $?
