//
//  _error_def.h
//  worldManager
//
//  Created by duanxiuyun on 14-12-19.
//  Copyright (c) 2014 duanxiuyun. All rights reserved.
//


ErrorElement( ESERVER_ERR_MYSQL ) ,
ErrorElement( ESERVER_ERR_HOST_UNAVAILABLE),
ErrorElement( ESERVER_ERR_TIMEOUT) ,
ErrorElement( ESERVER_ERR_SYSTEM) ,
ErrorElement( ESERVER_ERR_USERNAME), 
ErrorElement( ESERVER_ERR_NOUSER ),
ErrorElement( ESERVER_ERR_VERSION),
ErrorElement( ESERVER_ERR_INUSING),
ErrorElement( ESERVER_ERR_NAME_EXIST),
ErrorElement( ESERVER_ERR_SERVER_SHUTDOW),
ErrorElement( ESERVER_ERR_NEED_LOGIN),
ErrorElement( ESERVER_ERR_FORBID_LOGIN),
ErrorElement( ESERVER_ERR_LOGOUT),
ErrorElement( ESERVER_ERR_LOGIN_OTHER_CLIENT),
ErrorElement( ESERVER_ERR_SWITCH_SERVER),
ErrorElement( ESERVER_ERR_AIM_NOT_EXIST),
ErrorElement( ESERVER_ERR_SERVER_UNREADY),
ErrorElement( ESERVER_ERR_CANNOT_ENTER),
ErrorElement( ESERVER_ERR_NOT_IN_MAP),
ErrorElement( ESERVER_ERR_UNEXCEPTED_MSG),
ErrorElement(ESERVER_ERR_TOO_ROLES),
ErrorElement(ESERVER_ERR_SCRIPT_INSTRUCT),
ErrorElement(ESERVER_ERR_GAME_CONFIG),
ErrorElement(ESERVER_ERR_PACKAGE_FULL),
ErrorElement(ESERVER_ERR_SHORT_ITEM),
ErrorElement(ESERVER_ERR_NO_ITEM),
ErrorElement(ESERVER_ERR_LEVEL_LOW),
ErrorElement(ESERVER_ERR_FREE_TIME_OVER),
ErrorElement(ESERVER_ERR_SHORT_MONEY),
ErrorElement(ESERVER_ERR_VIP_LOWER),
ErrorElement(ESERVER_ERR_INPUT_VALID),

ErrorElement(ESERVER_ERR_NO_DRAGON),
ErrorElement(ESERVER_ERR_ITEM_STACK_LIMIT),

ErrorElement(ESERVER_ERR_IN_CD),

ErrorElement(ESERVER_ERR_MAX_LEVEL),
ErrorElement(ESERVER_ERR_NO_SKILL),
ErrorElement(ESERVER_ERR_ATTR_NOT_ENOUGH),
ErrorElement(ESERVER_ERR_ATTR_TOOL_MUCH),
ErrorElement(ESERVER_ERR_NO_WEAPON),
ErrorElement(ESERVER_ERR_SHOP_NOT_EXIST),
ErrorElement(ESERVER_ERR_AWARDS_GOT),
ErrorElement(ESERVER_ERR_CANNOT_GET_THIS_TASK),

ErrorElement(ESERVER_ERR_SIGNED_IN),

ErrorElement(ESERVER_ERR_NO_THIS_TASK),
ErrorElement(ESERVER_ERR_NEED_PASS_MAP),

ErrorElement(ESERVER_ERR_TASK_NOT_COMPLETED),

ErrorElement(ESERVER_ERR_ACHIEVMENT_NOT_COMPLETED),


ErrorElement(ESERVER_ERR_ITEM_OUT_SALE),
ErrorElement(ESERVER_ERR_TASK_IN_RUNNING),

ErrorElement(ESERVER_ERR_INVITE_CODE_INVALID),
ErrorElement(ESERVER_ERR_INVITE_BE_INVITED),
ErrorElement(ESERVER_ERR_INVITE_NOT_BE_INVITED),

ErrorElement(ESERVER_ERR_STATE_ERROR),
ErrorElement(ESERVER_ERR_PVP_AIM_IN_BATTLE),
ErrorElement(ESERVER_ERR_PVP_ALREADY_TOP1),



ErrorElement(ESERVER_ERR_NUMBER),
